import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/user_model.dart';
import '../../features/transactions/transactions_provider.dart';

class StatementGenerator {
  static Future<void> generateAndShare({
    required UserModel user,
    required List<TransactionModel> transactions,
  }) async {
    try {
      final tempDir = await getTemporaryDirectory();
      final file = File('${tempDir.path}/777_USDT_Gateway_Statement_${DateTime.now().millisecondsSinceEpoch}.pdf');

      // Writing a premium text-based report representing a mock PDF statement.
      // (In full production, this is generated by backend or using the pdf package)
      final StringBuffer buffer = StringBuffer();
      buffer.writeln('=============================================');
      buffer.writeln('      777 USDT GATEWAY INDIA STATEMENT     ');
      buffer.writeln('=============================================');
      buffer.writeln('Generated On: ${DateTime.now().toLocal()}');
      buffer.writeln('Merchant Name: ${user.name}');
      buffer.writeln('Mobile:       ${user.phone}');
      buffer.writeln('Email:        ${user.email}');
      buffer.writeln('=============================================');
      buffer.writeln('DATE        | USDT   | RATE  | INR PAYOUT | STATUS');
      buffer.writeln('---------------------------------------------');
      
      for (final tx in transactions) {
        final dateStr = tx.createdAt.substring(0, 10);
        final usdt = tx.amountUsdt.toString().padRight(6);
        final rate = tx.rateLockedInr.toStringAsFixed(2).padRight(5);
        final inr = (tx.amountUsdt * tx.rateLockedInr).toStringAsFixed(0).padRight(10);
        final status = tx.status.toUpperCase();
        buffer.writeln('$dateStr | $usdt | $rate | ₹$inr | $status');
      }
      
      buffer.writeln('=============================================');
      buffer.writeln('Total Trades Executed: ${transactions.length}');
      buffer.writeln('Thank you for choosing 777 USDT Gateway India.');
      
      await file.writeAsString(buffer.toString());

      // Share via native share sheet
      await Share.shareXFiles(
        [XFile(file.path, mimeType: 'application/pdf')],
        text: 'My 777 USDT Gateway India ledger statement',
      );
    } catch (e) {
      // Handle error
    }
  }
}
